# Generated by Django 4.2.2 on 2023-06-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_alter_team_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
