# Generated by Django 4.2.2 on 2023-06-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_rename_desc_team_desc1_rename_img_team_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img1',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
