# Generated by Django 4.2.2 on 2023-06-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_alter_team_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc1',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img1',
            new_name='img2',
        ),
    ]
